services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=RootM@@dle!74
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=Bn_m@@dle!74
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: lthub/moodle
    environment:
      - MOODLE_DB_HOST=mariadb
      - MOODLE_DB_PORT_NUMBER=3306
      - MOODLE_DB_USER=bn_moodle
      - MOODLE_DB_PASSWORD=Bn_m@@dle!74
      - MOODLE_DB_NAME=bitnami_moodle
      - MOODLE_REVERSEPROXY=yes
      # Optionnel (évite la génération de certifs dans le conteneur)
      - MOODLE_ENABLE_HTTPS=no
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
